apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    isDefault: true
    editable: true
    url: http://${DOCKER_INFLUXDB_INIT_HOST}:${DOCKER_INFLUXDB_INIT_PORT}
    secureJsonData:
      token: ${INFLUXDB_INIT_ADMIN_TOKEN}
    jsonData:
      version: Flux
      organization: ${INFLUXDB_INIT_ORG}
      defaultBucket: ${INFLUXDB_INIT_BUCKET}
      tlsSkipVerify: true